name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

   runs-on: [windows-latest]
   strategy:
      matrix:
        dotnet: [ '4.6.1', '2.1.x', '3.1.x', '5.0.x' ]
   name: Dotnet ${{ matrix.dotnet }}
   
   steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore CloudConvert.sln

    - name: Build the Solution
      run: msbuild CloudConvert.sln /p:Configuration=Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --f ${{ matrix.dotnet }}
